<?php
// ide-php settings, modify for your use.
define("WORKING_DIRECTORY", ".");
define("WEB_URL", "http://localhost:9000/ide.php");
define("TERMINAL_HOST", "0.0.0.0");
define("TERMINAL_PORT", "9001");
define("TERMINAL_COMMAND", "/bin/sh -i");
define("TERMINAL_WEBSOCKET_URL", "ws://localhost:9001");
define("TERMINAL_FIX_CRLF", true);
define("ENCRYPTION_KEY", "6UQkyq8wtb09gDRLoVrigO7WneJE00b3"); // CHANGE THIS!
define("ENCRYPTION_SALT", "VrigO7WneJE00b36UQkyq8wtb09gDRLo"); // CHANGE THIS!

//THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT LINES BELOW

/*This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
