<?php ob_start(); echo "<"; ?>?php
/*
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

----
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT LINES BELOW. 
SEE src/build.php FOR DETAILS ABOUT AUTOMATIC GENERATION.
*/
if (!file_exists("ide.config.php")) {
file_put_contents("ide.config.php", '<' . '?php
if (!defined("INCLUDE_CONFIG")) { die; }
define("WORKING_DIRECTORY", ".");
define("WEB_URL", "http://localhost:9000/ide.php");
define("TERMINAL_IP", "0.0.0.0");
define("TERMINAL_PORT", "9001");
define("TERMINAL_COMMAND", "/bin/sh -i");
define("TERMINAL_WEBSOCKET_URL", "ws://localhost:9001");
define("TERMINAL_FIX_CRLF", true);
define("ENCRYPTION_KEY", "6UQkyq8wtb09gDRLoVrigO7WneJE00b3"); // CHANGE THIS!
define("ENCRYPTION_SALT", "VrigO7WneJE00b36UQkyq8wtb09gDRLo"); // CHANGE THIS!
date_default_timezone_set("Europe/Istanbul");');
}
define("INCLUDE_CONFIG", true);
require("ide.config.php");
<?php

echo 'if (isset($_GET["css"])) { header("Content-Type: text/css"); ?'.'>';
foreach(glob("src/css/*.css") as $css) { readfile($css); }
echo "<"."? die; }\n";

echo 'if (isset($_GET["js"])) { header("Content-Type: application/javascript"); ?'.'>';
foreach(glob("src/js/lib/*.js") as $js) { readfile($js); echo ";"; }
foreach(glob("src/js/*.js") as $js) { readfile($js); echo ";"; }
echo "<"."? die; }\n";

echo 'if (isset($_GET["png"])) { 
	header("Content-Type: image/png"); 
	switch ($_GET["png"]) {
';
foreach(glob("src/png/*.png") as $png) { 
	echo "case '".basename($png)."': echo base64_decode('".base64_encode(file_get_contents($png))."'); break;\n";
}
echo "} die; }\n";

foreach(glob("src/php/*.php") as $php) { 
	$f = fopen($php, "r");
	fgets($f); // discard first line with <?php
	while(!feof($f)) { echo fgets($f); } 
	fclose($f); 
}

file_put_contents("ide.php", ob_get_clean());
